# Generated by Django 5.0.1 on 2024-01-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
